FUNCTION "CallManualOperationLineStartup" : Void
{ S7_Optimized_Access := 'TRUE' ; Published := 'FALSE' }
VERSION : 0.1

BEGIN
	REGION Description
	(*
	    Startup call to set the configuration of the Manual Operation Line for the Equipment modules
	*)
	    
	END_REGION
	
	"LAF_InternalManual".emsWithManualOpConfigured.maxNoOfEms := "NO_OF_EM";
	
	REGION Unit 1 Equipment Module 0 configuration
	    "ManualOperationControl_U1Em0".manualOperationEm.equipmentModuleNum := 1010;
	    "ManualOperationControl_U1Em0".manualOperationEmArea[2].displayedLines := '1-;';
	    "ManualOperationControl_U1Em0".manualOperationEmArea[1].displayedLines := '21-27;';
	END_REGION
	
	REGION Unit 1 Equipment Module 1 configuration
	    "ManualOperationControl_U1Em1".manualOperationEm.equipmentModuleNum := 1020;
	    "ManualOperationControl_U1Em1".manualOperationEmArea[2].displayedLines := '1-;';
	    "ManualOperationControl_U1Em1".manualOperationEmArea[1].displayedLines := '21-27;';
	END_REGION
	
	REGION Unit 1 Equipment Module 2 configuration
	    "ManualOperationControl_U1Em2".manualOperationEm.equipmentModuleNum := 1030;
	    "ManualOperationControl_U1Em2".manualOperationEmArea[2].displayedLines := '1-4;';
	    "ManualOperationControl_U1Em2".manualOperationEmArea[1].displayedLines := '21-22;';
	END_REGION
	
	REGION Unit 1 Equipment Module 3 configuration
	    "ManualOperationControl_U1Em3".manualOperationEm.equipmentModuleNum := 1040;
	    "ManualOperationControl_U1Em3".manualOperationEmArea[2].displayedLines := '1-2;';
	    "ManualOperationControl_U1Em3".manualOperationEmArea[1].displayedLines := '21-31;';
	END_REGION
	
	REGION Unit 1 Equipment Module 4 configuration
	    "ManualOperationControl_U1Em4".manualOperationEm.equipmentModuleNum := 1050;
	    "ManualOperationControl_U1Em4".manualOperationEmArea[2].displayedLines := '1-4;';
	    "ManualOperationControl_U1Em4".manualOperationEmArea[1].displayedLines := '21-33;';
	END_REGION
	
	REGION Unit 1 Equipment Module 5 configuration
	    "ManualOperationControl_U1Em5".manualOperationEm.equipmentModuleNum := 1060;
	    "ManualOperationControl_U1Em5".manualOperationEmArea[2].displayedLines := '1-6;';
	    "ManualOperationControl_U1Em5".manualOperationEmArea[1].displayedLines := '21-22;';
	END_REGION
	
	REGION Unit 1 Equipment Module 6 configuration
	    "ManualOperationControl_U1Em6".manualOperationEm.equipmentModuleNum := 1070;
	    "ManualOperationControl_U1Em6".manualOperationEmArea[2].displayedLines := '1;';
	    "ManualOperationControl_U1Em6".manualOperationEmArea[1].displayedLines := '21-24;';
	END_REGION
	
	REGION Unit 1 Equipment Module 7 configuration
	    "ManualOperationControl_U1Em7".manualOperationEm.equipmentModuleNum := 1080;
	    "ManualOperationControl_U1Em7".manualOperationEmArea[2].displayedLines := '1;';
	    "ManualOperationControl_U1Em7".manualOperationEmArea[1].displayedLines := '21-24;';
	END_REGION
	
	 REGION Unit 1 Equipment Module 8 configuration
	     "ManualOperationControl_U1Em8".manualOperationEm.equipmentModuleNum := 1090;
	     "ManualOperationControl_U1Em8".manualOperationEmArea[2].displayedLines := '1-2;';
	     "ManualOperationControl_U1Em8".manualOperationEmArea[1].displayedLines := '21-27;';
	END_REGION
	
	REGION Unit 1 Equipment Module 9 configuration
	    "ManualOperationControl_U1Em9".manualOperationEm.equipmentModuleNum := 1100;
	    "ManualOperationControl_U1Em9".manualOperationEmArea[2].displayedLines := '1-;';
	    "ManualOperationControl_U1Em9".manualOperationEmArea[1].displayedLines := '21-22;';
	END_REGION
	REGION Unit 1 Equipment Module 10 configuration
	    "ManualOperationControl_U1Em10".manualOperationEm.equipmentModuleNum := 1110;
	    "ManualOperationControl_U1Em10".manualOperationEmArea[2].displayedLines := '1-;';
	    "ManualOperationControl_U1Em10".manualOperationEmArea[1].displayedLines := '21-22;';
	END_REGION
	REGION Unit 1 Equipment Module 11 configuration
	    "ManualOperationControl_U1Em11".manualOperationEm.equipmentModuleNum := 1120;
	    "ManualOperationControl_U1Em11".manualOperationEmArea[2].displayedLines := '1-;';
	    "ManualOperationControl_U1Em11".manualOperationEmArea[1].displayedLines := '21-22;';
	END_REGION
	
	REGION Unit 1 Equipment Module 12 configuration
	    "ManualOperationControl_U1Em12".manualOperationEm.equipmentModuleNum := 1130;
	    "ManualOperationControl_U1Em12".manualOperationEmArea[2].displayedLines := '1-;';
	    "ManualOperationControl_U1Em12".manualOperationEmArea[1].displayedLines := '21-27;';
	END_REGION
	
	REGION Unit 1 Equipment Module 13 configuration
	    "ManualOperationControl_U1Em13".manualOperationEm.equipmentModuleNum := 1140;
	    "ManualOperationControl_U1Em13".manualOperationEmArea[2].displayedLines := '1-3;';
	    "ManualOperationControl_U1Em13".manualOperationEmArea[1].displayedLines := '21;';
	END_REGION
	
	(* REGION Unit 1 Equipment Module 14 configuration
	    "ManualOperationControl_U1Em14".manualOperationEm.equipmentModuleNum := 1150;
	    "ManualOperationControl_U1Em14".manualOperationEmArea[2].displayedLines := '1-;';
	    "ManualOperationControl_U1Em14".manualOperationEmArea[1].displayedLines := '13-18;';
	END_REGION
	
	REGION Unit 1 Equipment Module 15 configuration
	    "ManualOperationControl_U1Em15".manualOperationEm.equipmentModuleNum := 1160;
	    "ManualOperationControl_U1Em15".manualOperationEmArea[2].displayedLines := '1-;';
	    "ManualOperationControl_U1Em15".manualOperationEmArea[1].displayedLines := '13-18;';
	END_REGION 
	*)
END_FUNCTION

